ThePrimeagen/refactoring.nvim

- lua/refactoring/region.lua
Creates `Region` class.
Not sure all of the logic is right yet, but we can change things however you want for that.
> feat: Add region

- lua/refactoring/106.lua
- scratch/test.lua
https://user-images.githubusercontent.com/4466899/126839903-03030f87-bff3-4727-b15b-6d2fbd8573d0.mp4
> auto name it

- queries/typescript/refactoring.scm
There is a way to match with a single query.
> TypeScript Query Simplifying

- README.md
- lua/refactoring/utils.lua
> feat(readme): how to setup WIP

- lua/refactoring/config.lua
- lua/refactoring/region.lua
- lua/refactoring/tests/extract.simple-function.commands
- lua/refactoring/tests/extract.simple-function.expected.ts
- lua/refactoring/tests/extract.simple-function.start.ts
- lua/refactoring/tests/refactor_spec.lua
- lua/refactoring/tests/region_spec.lua
> feat: testing

- lua/refactoring/pipeline/get_selected_local_defs.lua
- lua/refactoring/pipeline/refactor_setup.lua
- lua/refactoring/pipeline/selection_setup.lua
- lua/refactoring/query.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/utils.lua
We should be able to add a few other items, the find occurances and
other sexpr operations and make this a lot easier to test
> feat: query object.

- lua/refactoring/tests/motion.lua
- lua/refactoring/tests/region_spec.lua
motion command now does the "motion" for you
> feat: hated vim motions in tests

- lua/refactoring/query.lua
- lua/refactoring/tests/extract.simple-function.expected.lua
- lua/refactoring/tests/extract.simple-function.lua.commands
- lua/refactoring/tests/extract.simple-function.start.lua
- lua/refactoring/tests/motion.lua
- lua/refactoring/tests/query.ts
- lua/refactoring/tests/query_spec.lua
- lua/refactoring/tests/refactor_spec.lua
- lua/refactoring/tests/region_spec.lua
- lua/refactoring/tests/utils.lua
At least the find_occurances are tested :)  Next will be scope test
cases
> feat: query tests

- lua/refactoring/utils.lua
fixed the wrong comments of the function
> fixed wrong function comments

- Makefile
- lua/refactoring/tests/minimal.vim
Adding makefile to make contributions easier with formatting lua, running tests, and making project PR ready. There was mention in the discord of using premake which I can look into as well. If you don't like this approach this PR could be scrapped as well.
> Adding basic Makefile with fmt, test, pr-ready command

- lua/refactoring/tests/query.ts
- lua/refactoring/tests/query_spec.lua
- lua/refactoring/utils.lua
Wanted to make sure that we can trim strings.  Because lua.
> feat: trim string

- lua/refactoring/config.lua
- lua/refactoring/query.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/tests/extract_var.example.expected.ts
- lua/refactoring/tests/extract_var.example.start.ts
- lua/refactoring/tests/extract_var.example.ts.commands
- lua/refactoring/utils.lua
- queries/typescript/refactoring.scm
119 - Extract Var - Before
119 - After!!!
> feat: 119 in typescript

- lua/refactoring/code_generation/lua.lua
> feat: extract var for lua

- lua/refactoring/code_generation/go.lua
- lua/refactoring/code_generation/lua.lua
- lua/refactoring/code_generation/python.lua
- lua/refactoring/code_generation/typescript.lua
- lua/refactoring/code_generation/utils.lua
- lua/refactoring/pipeline/refactor_setup.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/tests/extract.simple-function.expected.go
- lua/refactoring/tests/extract.simple-function.expected.lua
- lua/refactoring/tests/extract.simple-function.expected.py
- lua/refactoring/tests/extract.simple-function.expected.ts
This should make adding new features / indenting / language specific
things easier.
> refactor: code gen is now dumber than it was before.

- README.md
I like telescope opts. I want people to know to use them as well.
> readme: set and pass telescope opts

- lua/refactoring/pipeline/lsp_definition_setup.lua
- lua/refactoring/refactor/123.lua
- lua/refactoring/tasks/ensure_lsp_definition_in_buffer.lua
- lua/refactoring/utils.lua
@alvarotroya I did move the new task into the tasks folder so that should prevent to much conflicts / extra work :)
> feat: lsp definition checking task.

- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/tests/refactor_spec.lua
Also performed some refactoring of tests to make it easier to create these test cases. Might move validation into get input, but that might break tests in current structure. Also noticed that extract function to file has no tests, let me know if I should make issue for that. 
Addresses #62
> feat: Added validation for input of extract function and var

- Makefile
> Add luacheck to Makefile. Add luacheck to pr-ready task

- README.md
I saw this mentioned in one of the issues. It was non-obvious to me, so I put it in the readme.
> Note on supported languages in readme

- .github/workflows/test.yml
- lua/refactoring/lsp_utils.lua
- lua/refactoring/tests/lsp_utils_spec.lua
- lua/refactoring/utils.lua
Its really hard to test these for now.  I am unsure where to go from
here without a bit better knowledge of how the lsp works with testing.
Perhaps Telescopic "Big LSP" Johnson will know.
> feat: lsp-utils.

- lua/refactoring/tests/refactor/119/go/example/extract_var.commands
- lua/refactoring/tests/refactor/119/go/example/extract_var.expected.go
- lua/refactoring/tests/refactor/119/go/example/extract_var.inputs
- lua/refactoring/tests/refactor/119/go/example/extract_var.start.go
- queries/go/refactoring.scm
Noticed there is an issue running refactor_spec.lua alone due to nil scope.  Looks related to something in tests as the failing test had no changes in this PR, but `make test` is passing. Let me know if you want me to look into that before merging.
#42
> feat: add golang support for 119

- lua/refactoring/config.lua
- lua/refactoring/tests/minimal.vim
- lua/refactoring/tests/refactor/119/go/example/extract_var.commands
- lua/refactoring/tests/refactor/119/ts/example/extract_var.commands
Not sure why old commands were failing, but through debugging this appears to resolve issue.
> fix: Fixing issue with extract var tests failing

- lua/refactoring/code_generation/typescript.lua
- lua/refactoring/config.lua
- lua/refactoring/debug/printf.lua
- lua/refactoring/point.lua
- lua/refactoring/tasks/apply_text_edits.lua
- lua/refactoring/treesitter/treesitter.lua
- lua/refactoring/treesitter/typescript.lua
@teddylear the code sucks, but it was done fast and live.  :)
> feat: debug printer.

- .github/workflows/format.yml
- lua/refactoring/tests/lsp_utils_spec.lua
- lua/refactoring/tests/utils_spec.lua
- lua/refactoring/treesitter/treesitter.lua
- scratch/test.lua
testing 1 2 3 please check branch name
> fix: go fast for stylua

- lua/refactoring/debug/printf.lua
- lua/refactoring/pipeline/init.lua
- lua/refactoring/point.lua
- lua/refactoring/query.lua
- lua/refactoring/query2.lua
- lua/refactoring/region.lua
- lua/refactoring/treesitter/treesitter.lua
- lua/refactoring/treesitter/typescript.lua
- lua/refactoring/version.lua
Haven't cleaned up or exposed them correctly, but you can see what is happening.
> feat: Add node style of config

- lua/refactoring/code_generation/cpp.lua
- lua/refactoring/code_generation/init.lua
- lua/refactoring/treesitter/cpp.lua
- lua/refactoring/treesitter/init.lua
- lua/refactoring/treesitter/nodes.lua
@tjdevries I have mutated things a bit.  you know. cpp has to be hard.
I also cannot get style to work properly now.  I am executing stylua yet I am not getting the same thing...
> feat: cpp printf

- lua/refactoring/treesitter/nodes.lua
- lua/refactoring/treesitter/typescript.lua
Somethin like this:
```ts
const stupidWayToSpecifyAFunction = () => {
function outerFunction() {
class Test {
private test: number = 0;
constructor() {
(() =>{
// got this to work
console.log("stupidWayToSpecifyAFunction#outerFunction#Test#constructor#(anon)");
})();
"This is a method Definition"
}
}
}
}
```
> feat(typescript): Detect ()=>{} name if possible

- queries/javascript/refactoring.scm
- queries/typescript/refactoring.scm
See Docs (wildcard node): https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries
> fix: Update ts and js queries to have correct wildcard character

- lua/refactoring/tests/debug/printf/cpp/class-function/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/destructor/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/inline-class-function/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/simple-function/printf.expected.cpp
- scripts/find-supported-languages.sh
Fix CI for install parsers and cpp debug tests.
> Fix ci cpp printf

- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/refactor/123.lua
- lua/refactoring/treesitter/treesitter.lua
refactor: move all pluck by captures to treesitter so they are eventually replaced by nodes
> refactor: move all pluck by captures to treesitter so they are eventually replaced by nodes

- lua/refactoring/refactor/119.lua
- lua/refactoring/tests/treesitter/treesitter_spec.lua
- lua/refactoring/treesitter/cpp.lua
- lua/refactoring/treesitter/golang.lua
- lua/refactoring/treesitter/nodes.lua
- lua/refactoring/treesitter/treesitter.lua
- lua/refactoring/treesitter/typescript.lua
- queries/cpp/refactoring.scm
- queries/go/refactoring.scm
- queries/typescript/refactoring.scm
feat: Attempt Inline Nodes and move statements to use it
> feat: Attempt Inline Nodes and move statements to use it

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- lua/refactoring/refactor/106.lua
- lua/refactoring/tests/refactor/106/go/prompt_func_param/extract.inputs
- lua/refactoring/tests/refactor/106/go/prompt_func_param_no_return/extract.inputs
- lua/refactoring/tests/refactor/106/go/prompt_func_param_return/extract.inputs
- lua/refactoring/tests/refactor/106/go/prompt_func_return/extract.expected.go
- lua/refactoring/tests/refactor/106/go/return/extract.expected.go
- lua/refactoring/tests/refactor/106/go/simple-function/extract.expected.go
- lua/refactoring/tests/refactor/106/go/struct-2/extract.expected.go
- lua/refactoring/tests/refactor/106/go/struct-return/extract.expected.go
- lua/refactoring/tests/refactor/106/go/struct/extract.expected.go
- lua/refactoring/treesitter/langs/go.lua
- lua/refactoring/treesitter/treesitter.lua
types of parameters in current function being based. Only golang support
for now
> feat: For languages that require param types for functions, try to find

- README.md
Made this PR after [this discord message](https://discord.com/channels/478925420616482816/870767140389662730/919787124318957688).
Better late than never!e
This quote is from Refactoring (second edition) by Martin Fowler. It can be found in Chapter 2 - Problems With Refactoring: Testing. In my book is page 59.
Full paragraph goes like this:
*There is another way to deal with the testing problem. **If I use an environment that has good automated refactorings, I can trust those refactorings** even without running tests. I can then refactor, providing I only use those refactorings that are safely automated. This removes a lot of nice refactorings from my menu, but still leaves me enough to deliver some useful benefits. I'd still rather have self-testing code, but it's an option that is useful …
> Include quote from Martin Fowler in README

- README.md
> docs(add-function-docs): added descriptions for refactor functions to README

- README.md
Whoops, forgot to add Java to the README.
> docs(README): added java to readme

- lua/refactoring/code_generation/langs/php.lua
- lua/refactoring/config/init.lua
- lua/refactoring/tests/refactor/119/php/example/extract_var.commands
- lua/refactoring/tests/refactor/119/php/example/extract_var.expected.php
- lua/refactoring/tests/refactor/119/php/example/extract_var.expected.ts
- lua/refactoring/tests/refactor/119/php/example/extract_var.inputs
- lua/refactoring/tests/refactor/119/php/example/extract_var.start.php
- lua/refactoring/treesitter/langs/php.lua
I messed something up during the rebasing on my original PR. so here's a new one. 119 should now work as intended. (there is a weird indent thing, but as far as I can see that's on all branches)
> feat: php 119

- lua/refactoring/code_generation/langs/typescript.lua
- lua/refactoring/tests/refactor/106/ts/class/extract.expected.ts
- lua/refactoring/tests/refactor/106/ts/multiple-returns/extract.expected.ts
- lua/refactoring/tests/refactor/106/ts/simple-function/extract.expected.ts
- lua/refactoring/tests/refactor/106/ts/single-return/extract.expected.ts
- lua/refactoring/tests/refactor/106/ts/with-comments/extract.expected.ts
- lua/refactoring/treesitter/langs/typescript.lua
- Typescript func indenting
- Set parameter type if already present
> Typescript func indenting

- lua/refactoring/debug/cleanup.lua
- lua/refactoring/debug/print_var.lua
- lua/refactoring/debug/printf.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/refactor/123.lua
- lua/refactoring/refactor/178.lua
- lua/refactoring/refactor/init.lua
- lua/refactoring/tasks/post_refactor.lua
> Extract Block to File

- lua/refactoring/debug/cleanup.lua
- lua/refactoring/tests/debug/cleanup/c/cleanup.expected.c
- lua/refactoring/tests/debug/cleanup/cpp/cleanup.expected.cpp
- lua/refactoring/tests/debug/cleanup/go/cleanup.expected.go
- lua/refactoring/tests/debug/cleanup/java/cleanup.expected.java
- lua/refactoring/tests/debug/cleanup/js/cleanup.expected.js
- lua/refactoring/tests/debug/cleanup/lua/cleanup.expected.lua
- lua/refactoring/tests/debug/cleanup/py/cleanup.expected.py
- lua/refactoring/tests/debug/cleanup/py/cleanup.start.py
- lua/refactoring/tests/debug/cleanup/ts/cleanup.expected.ts
@pranavrao145 
feat: remove line during debug cleanup for all rows but first row
#271
> feat: remove line during debug cleanup for all rows but first row

- lua/refactoring/debug/print_var.lua
- lua/refactoring/tests/debug/print_var/c/mutiple-statements/print_var.expected.c
- lua/refactoring/tests/debug/print_var/c/simple-function/print_var.expected.c
- lua/refactoring/tests/debug/print_var/cpp/class-function/print_var.expected.cpp
- lua/refactoring/tests/debug/print_var/cpp/mutiple-statements/print_var.expected.cpp
- lua/refactoring/tests/debug/print_var/cpp/simple-function/print_var.expected.cpp
- lua/refactoring/tests/debug/print_var/go/multiple-statements/print_var.expected.go
- lua/refactoring/tests/debug/print_var/go/simple-function/print_var.expected.go
- lua/refactoring/tests/debug/print_var/java/class-function/print_var.expected.java
- lua/refactoring/tests/debug/print_var/java/multiple-statements/print_var.expected.java
- lua/refactoring/tests/debug/print_var/js/class-function/print_var.expected.js
- lua/refactoring/tests/debug/print_var/js/multiple-statements/print_var.expected.js
- lua/refactoring/tests/debug/print_var/js/simple-function/print_var.expected.js
- lua/refactoring/tests/debug/print_var/lua/multiple-statements/print_var.expected.lua
- lua/refactoring/tests/debug/print_var/lua/simple-function/print_var.expected.lua
- lua/refactoring/tests/debug/print_var/php/multiple-statements/print_var.expected.php
- lua/refactoring/tests/debug/print_var/php/simple-function/print_var.expected.php
- lua/refactoring/tests/debug/print_var/py/multiple-statements/print_var.expected.py
- lua/refactoring/tests/debug/print_var/py/simple-function/print_var.expected.py
- lua/refactoring/tests/debug/print_var/ts/class-function/print_var.expected.ts
- lua/refactoring/tests/debug/print_var/ts/multiple-statements/print_var.expected.ts
- lua/refactoring/tests/debug/print_var/ts/simple-function/print_var.expected.ts
@pranavrao145 
feat: add indentation to print_var
Please let me know if I should change anything
#309
> feat: add indentation to print_var

- lua/refactoring/tests/debug/print_var/c/simple-function-nor-mode/print_var.expected.c
- lua/refactoring/tests/debug/print_var/cpp/simple-function-nor-mode/print_var.expected.cpp
- lua/refactoring/tests/debug/print_var/go/simple-function-nor-mode/print_var.expected.go
- lua/refactoring/tests/debug/print_var/js/simple-function-nor-mode/print_var.expected.js
- lua/refactoring/tests/debug/print_var/lua/simple-function-nor-mode/print_var.expected.lua
- lua/refactoring/tests/debug/print_var/php/simple-function-nor-mode/print_var.expected.php
- lua/refactoring/tests/debug/print_var/py/simple-function-nor-mode/print_var.expected.py
fix: update indenting on print_var tests for normal mode
> fix: update indenting on print_var tests for normal mode

- lua/refactoring/debug/printf.lua
- lua/refactoring/tests/debug/printf/c/simple-function/printf.expected.c
- lua/refactoring/tests/debug/printf/cpp/destructor/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/simple-function/printf.expected.cpp
- lua/refactoring/tests/debug/printf/go/multiple-statements/printf.expected.go
- lua/refactoring/tests/debug/printf/go/multiple-statements/printf.start.go
- lua/refactoring/tests/debug/printf/go/simple-function/printf.expected.go
- lua/refactoring/tests/debug/printf/java/class-function/printf.expected.java
- lua/refactoring/tests/debug/printf/java/multiple-statements/printf.expected.java
- lua/refactoring/tests/debug/printf/js/simple-function/printf.expected.js
- lua/refactoring/tests/debug/printf/lua/multiple-statements/printf.expected.lua
- lua/refactoring/tests/debug/printf/lua/simple/printf.expected.lua
- lua/refactoring/tests/debug/printf/py/simple/printf.expected.py
- lua/refactoring/tests/debug/printf/ts/simple-function/printf.expected.ts
Adding indenting printf
Normally would rebase, but I tried and it got way too ugly... leaving as is this one time. 
@pranavrao145
> Adding indenting printf

- lua/refactoring/tests/refactor_spec.lua
- lua/refactoring/tests/utils.lua
feat: Add ability to skip test cases to not block new development for minor upstream parser changes
> feat: Add ability to skip test cases to not block new development for minor upstream parser changes

- lua/refactoring/refactor/106.lua
- lua/refactoring/tests/refactor/106/c/extract-block/extract_block.expected.c
- lua/refactoring/tests/refactor/106/cpp/extract-block/extract_block.expected.cpp
- lua/refactoring/tests/refactor/106/go/extract-block/extract_block.expected.go
- lua/refactoring/tests/refactor/106/java/extract_block/extract_block.expected.java
- lua/refactoring/tests/refactor/106/js/extract-block/extract_block.expected.js
- lua/refactoring/tests/refactor/106/lua/extract-block/extract_block.expected.lua
- lua/refactoring/tests/refactor/106/py/extract-block/extract_block.expected.py
- lua/refactoring/tests/refactor/106/rb/extract_block-1/extract_block.expected.rb
- lua/refactoring/tests/refactor/106/rb/extract_block-2/extract_block.expected.rb
- lua/refactoring/tests/refactor/106/ts/extract-block/extract_block.expected.ts
This fixes the indentation for extract_block, but I'm not sure if this is the best aproach in doing it.
This is half of the solution for  #352
> Fix: indentation for extract_block

- lua/refactoring/debug/printf.lua
- lua/refactoring/tests/debug/printf/c/multiple-statements/printf.expected.c
- lua/refactoring/tests/debug/printf/cpp/destructor/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/inline-class-function/printf.expected.cpp
- lua/refactoring/tests/debug/printf/cpp/multiple-statements/printf.expected.cpp
- lua/refactoring/tests/debug/printf/go/multiple-statements/printf.expected.go
- lua/refactoring/tests/debug/printf/go/multiple-statements/printf.start.go
- lua/refactoring/tests/debug/printf/java/class-function/printf.expected.java
- lua/refactoring/tests/debug/printf/java/class-function/printf.start.java
- lua/refactoring/tests/debug/printf/js/multiple-statements/printf.expected.js
- lua/refactoring/tests/debug/printf/py/multiple-statements/printf.expected.py
- lua/refactoring/tests/debug/printf/rb/complex-function/printf.expected.rb
- lua/refactoring/tests/debug/printf/rb/complex-function/printf.start.rb
- lua/refactoring/tests/debug/printf/rb/multiple-statements/printf.expected.rb
- lua/refactoring/tests/debug/printf/rb/multiple-statements/printf.start.rb
- lua/refactoring/tests/debug/printf/rb/simple-function/printf.expected.rb
- lua/refactoring/tests/debug/printf/rb/simple-function/printf.start.rb
- lua/refactoring/tests/debug/printf/ts/multiple-statements/printf.expected.ts
- lua/refactoring/treesitter/langs/cpp.lua
- lua/refactoring/treesitter/langs/lua.lua
- lua/refactoring/treesitter/langs/php.lua
- lua/refactoring/treesitter/langs/python.lua
- lua/refactoring/treesitter/langs/ruby.lua
This should close #352, since now all the Python test are valid Python code.
Since I'm new to this part of the codebase, I'm not sure if everything I made on `printf.lua` is the correct way of doing it.
> Fix #352: new way to determine indentation for printf

- lua/refactoring/init.lua
- plugin/command.lua
Don't wait until user calls `setup` to load the `Refactor` command
> feat: load Refactor command on startup

- README.md
- lua/refactoring/config/init.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/refactor/123.lua
- lua/refactoring/tasks/post_refactor.lua
- lua/refactoring/tasks/refactor_setup.lua
> feat: optional success message on 106, 119 and 123

- lua/refactoring/code_generation/langs/lua.lua
- lua/refactoring/config/init.lua
- lua/refactoring/tests/debug/print_var/lua/indexed-expression/print_var.commands
- lua/refactoring/tests/debug/print_var/lua/indexed-expression/print_var.expected.lua
- lua/refactoring/tests/debug/print_var/lua/indexed-expression/print_var.start.lua
- lua/refactoring/tests/debug/print_var/lua/simple-function-nor-mode/print_var.expected.lua
- lua/refactoring/tests/debug/print_var/lua/simple-function/print_var.expected.lua
- lua/refactoring/tests/debug/printf/lua/multiple-statements/printf.expected.lua
- lua/refactoring/tests/debug/printf/lua/simple/printf.expected.lua
- lua/refactoring/treesitter/langs/c.lua
- lua/refactoring/treesitter/langs/cpp.lua
- lua/refactoring/treesitter/langs/go.lua
- lua/refactoring/treesitter/langs/java.lua
- lua/refactoring/treesitter/langs/javascript.lua
- lua/refactoring/treesitter/langs/javascriptreact.lua
- lua/refactoring/treesitter/langs/lua.lua
- lua/refactoring/treesitter/langs/php.lua
- lua/refactoring/treesitter/langs/python.lua
- lua/refactoring/treesitter/langs/ruby.lua
- lua/refactoring/treesitter/langs/typescript.lua
- lua/refactoring/treesitter/langs/typescriptreact.lua
> feat(print_var): support indexed expressions for go and lua

- lua/refactoring/code_generation/init.lua
- lua/refactoring/code_generation/langs/go.lua
- lua/refactoring/config/init.lua
- lua/refactoring/debug/debug_utils.lua
- lua/refactoring/debug/get_path.lua
- lua/refactoring/debug/print_var.lua
- lua/refactoring/debug/printf.lua
- lua/refactoring/notify.lua
- lua/refactoring/point.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/refactor/115.lua
- lua/refactoring/refactor/119.lua
- lua/refactoring/refactor/123.lua
- lua/refactoring/tasks/notify.lua
- lua/refactoring/tasks/selection_setup.lua
> feat: better error handling for code_generation

- lua/refactoring/treesitter/langs/go.lua
> fix(go): add var_declaration to variable_scope

- lua/refactoring/treesitter/langs/javascript.lua
- lua/refactoring/treesitter/langs/javascriptreact.lua
> fix(javascriptreact): remove typescript exclusive captures

- lua/refactoring/treesitter/langs/python.lua
> fix(python): add with_statement

- lua/refactoring/refactor/123.lua
- lua/refactoring/treesitter/langs/lua.lua
- lua/refactoring/treesitter/langs/python.lua
- lua/refactoring/treesitter/treesitter.lua
> fix(123): filter references using language specific function

- lua/refactoring/init.lua
> Fix(select_refactor): call void async function

- lua/refactoring/code_generation/langs/typescriptreact.lua
- lua/refactoring/refactor/106.lua
- lua/refactoring/tests/refactor/106/tsx/extract-block-simple-component/extract_block.expected.tsx
- lua/refactoring/tests/refactor/106/tsx/extract-simple-component/extract.expected.tsx
> fix(jsx/tsx): correctly inline component call

- lua/refactoring/treesitter/langs/javascriptreact.lua
- lua/refactoring/treesitter/langs/typescriptreact.lua
> feat(jsx/tsx 106): account for array and object destructuring variables

- lua/refactoring/treesitter/langs/javascript.lua
- lua/refactoring/treesitter/langs/typescript.lua
- lua/refactoring/treesitter/langs/typescriptreact.lua
- lua/telescope/_extensions/refactoring.lua
@viggin543 this should fix your issue with telescope
> fix: make telescope extension work again and small js improvements
