lua/refactoring/config.lua
lua/refactoring/region.lua
lua/refactoring/tests/extract.simple-function.expected.py
lua/refactoring/tests/extract.simple-function.py.commands
lua/refactoring/tests/extract.simple-function.start.py
lua/refactoring/tests/refactor_spec.lua
queries/python/refactoring.scm

Adding python support for extract function. Had to change `end_col` for `to_ts` for `Region` Class so that scope was correct for python. This is mentioned in a comment at the top of `Region` class. Appears to not have broken tests for region that exist, let me know if you want to update to something else.

feat: Adding python support for 106

---

lua/refactoring/tests/minimal.vim

Noticed on stream that `makefile test` was not working for you because of missing dependencies (probably others as well). Added plugin dependencies to `minimal.vim` file to resolve. Please run on your machine to let me know if this is now working, however this was working for me before these changes. That may be because of my nvim configuration though, but I'm not sure why. If this still fails for you I'll have to keep looking into this.

Updating minimal.vim for makefile testing

---

lua/refactoring/dev.lua
lua/refactoring/query.lua
lua/refactoring/refactor/119.lua
lua/refactoring/refactor/init.lua
lua/refactoring/region.lua
lua/refactoring/tests/extract_var.example.expected.ts
lua/refactoring/tests/extract_var.example.inputs
lua/refactoring/tests/extract_var.example.start.ts
lua/refactoring/tests/extract_var.example.ts.commands
lua/refactoring/tests/query_spec.lua
lua/refactoring/tests/refactor_spec.lua
lua/refactoring/utils.lua
queries/typescript/refactoring.scm

This is the bones of the PR.  It does make some actual progress into the extract var refactor.  The images below show where it gets to
Before.  Selecting `order.quantity * order.itemPrice`
After.  setting the new name to `basePrice`
There isn't the local basePrice = <selection> piece yet.

Extract var 2

---

lua/refactoring/tests/minimal.vim

If someone uses lunarvim for local development the packer directory is located in a different directory. This allows to run the tests with the local configuration, without the need to check out plenary and nvim-treesitter locally.

Add lunarvim to rtp in order to run tests locally

---

.github/workflows/test.yml
lua/refactoring/tests/minimal.vim

From what I gather "ensure_installed" does an async install, which makes tests run before the parsers are available. This works around that by using `TSInstallSync`.
Parser diffing happens, so that you're not prompted to reinstall a parser that's already available.
Additionally, I've hit a [bug in nvim/plenary](https://github.com/nvim-lua/plenary.nvim/issues/52), where output produced by `TSInstall*` kabooms the test run:
```
nvim: /build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/src/nvim/message.c:2284: msg_scroll_flush: Assertion `pos_delta >= 0' failed.
```
It perhaps lacks the coconut oiliness, but seems to work, so.. 🤷.

Run tests in CI

---

README.md

I added an escape to the mappings in the readme. This was at least my problem in #12. Escaping before running the commands leads to the marks of visual mode is updated, and it can then find the correct rows and columns of the visual area

readme: add escape to mappings

---

lua/refactoring/tests/lsp_utils_spec.lua
lua/refactoring/tests/refactor/123/ts/example/inline_var.commands
lua/refactoring/tests/refactor/123/ts/example/inline_var.expected.ts
lua/refactoring/tests/refactor/123/ts/example/inline_var.start.ts
lua/refactoring/tests/refactor_spec.lua
lua/refactoring/tests/utils.lua

Adding tests for inline var for typescript. Had to edit some logic about finding test files and separately those that require lsp and those that don't, this should be edited later to not be as hacky as how I wrote here. But for now this starts the ability to add `inline_var` tests.

chore: Adding tests for inline var for typescript

---

lua/refactoring/get_input.lua

This is a draft PR, needs some architectural changes to `Pipeline` due to the new api of `vim.ui.input`

Use vim.ui.input instead of vim.fn.input

---

lua/refactoring/init.lua

Accounted for case where opts passed to refactor function were nil.

Empty opts fix

---

lua/refactoring/config/init.lua

#140 
Enable calling `require('refactoring').setup()` without any args and prevent a `vim.tbl_deep_extend` with a `nil` value.

fix: handle setup call with no args

---

lua/refactoring/treesitter/treesitter.lua

This one line of code can be uncommented to find the parent nodes of a given selected node. This is especially useful in finding the top level node (for the global scope of a language), which doesn't show up in Playground. This would've been really useful for me in doing #166 and saved me hours, because I couldn't find the global node in the Playground or in any of the limited documentation for the C++ TS parser.

chore(dev): added inline code to find parent nodes of current node

---

lua/refactoring/refactor/123.lua

Right now, inline var is only designed to work when the cursor is on the identifier. If the cursor is not on an identifier, it actually does not error out, but instead produces a weird result. This PR adds an error message when the cursor is not on an identifier to prevent this from happening. This is more of a temporary fix; in the future I think we should try and make it so that it finds the identifier if a declaration is selected (that might take some more time).

fix(inline-var-cursor): added error message when not on identifier

---

lua/refactoring/code_generation/cpp.lua
lua/refactoring/tests/refactor/106/c/simple-function/extract.expected.c
lua/refactoring/tests/refactor/106/cpp/class-function/extract.expected.cpp
lua/refactoring/tests/refactor/106/cpp/simple-function/extract.expected.cpp

This PR replicates #171 (what was done for the golang function args) for C/C++ as well.

feat(c-cpp-func-args-types): added func arg types for c/cpp

---

README.md
lua/telescope/_extensions/refactoring.lua

This PR adds a Telescope extension to the project. This will make it easier for people to use Telescope with the plugin (essentially eliminating the manual configuration step in between).
The same 20-ish lines of config code that is in the README can now be shortened to:
```lua
require('telescope').load_extension("refactoring")
vim.api.nvim_set_keymap("v", "<leader>rr", "<Esc><cmd>lua require('telescope').extensions.refactoring.refactors()<CR>", { noremap = true })
```
I also intend to update the README with this change once #183 is merged.
**EDIT:** README is now also updated in this PR to reflect the Telescope extension.

feat(telescope-extension): created telescope extension

---

README.md

Just something I noticed while scrolling - there was an accidental duplicate comment in the README examples. Fixed now.

docs(README): fixed typo in README

---

lua/refactoring/tasks/apply_text_edits.lua
lua/refactoring/tests/lsp_utils_spec.lua

Fixed lsp_utils to work with the latest Neovim Nightly in accordance with the latest breaking changes in [this issue](https://github.com/neovim/neovim/issues/14090). This was previously causing all tests to fail, but all tests pass with this change.

fix(lsp-utils): fix lsp_utils in accordance with latest nvim breaking changes

---

lua/refactoring/refactor/123.lua

It was previously not inlining the variable, but simply deleting it.

fix(123-single-selection): fixed highlighting and inlining single declaration

---

lua/refactoring/query.lua

In cases where there are no treesitter parsers installed for the
current buffer, we can't do anything. This could happen in cases
where the user hasn't installed treesitter parser for the
specific language.
This should improve the user experience by telling them what to fix.
Issue #216

feat(query): Return an error if no parser found

---

lua/refactoring/code_generation/langs/c.lua
lua/refactoring/code_generation/langs/cpp.lua
lua/refactoring/code_generation/langs/go.lua
lua/refactoring/code_generation/langs/lua.lua
lua/refactoring/code_generation/langs/python.lua
lua/refactoring/code_generation/langs/typescript.lua
lua/refactoring/refactor/123.lua
lua/refactoring/tests/refactor/123/c/multiple-vars/inline_var.expected.c
lua/refactoring/tests/refactor/123/cpp/multiple-vars/inline_var.expected.cpp
lua/refactoring/tests/refactor/123/go/multiple-vars/inline_var.expected.go
lua/refactoring/tests/refactor/123/js/multiple-vars/inline_var.expected.js
lua/refactoring/tests/refactor/123/lua/multiple-vars/inline_var.expected.lua
lua/refactoring/tests/refactor/123/ts/multiple-vars/inline_var.expected.ts
lua/refactoring/treesitter/langs/go.lua

As an extension to #211, this PR will allow for the deletion of a singular variable when inlining for all supported languages. This PR closes #218.
- In C/C++, this functionality ignores the type of the variable and simply inserts the default type value for the new declaration. I intend to fix this at some point, but it is yet again far too much custom logic to put in this PR (especially because it deals with one particular filetype)
- Since Python was not supported in #211, it is not supported here either yet.
- 123 in general has become messy to a point I don't like anymore; at some point I will clean this up to look more like 106 (i.e. splitting everything up into more functions and simply calling the main function in the pipeline).

Inline Var: Delete single declaration

---

README.md

Inlining a variable also works in normal mode. I got a bit confused while testing this plugin for the first time and nothing happened in normal mode. So hopefully this makes it more explicit.

add keymap example for inlining in normal mode

---

.github/ISSUE_TEMPLATE/bug.yml

@ThePrimeagen @pranavrao145 
Creating an issue template for bugs based on [this github feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). Hopefully this makes creating bugs more straightforward. Not sure of a way to test this prior to merge, so I can merge and play around with getting it right if we are alright with doing this. I can add one for feature requests also.

Issue templates

---

lua/refactoring/code_generation/langs/python.lua
lua/refactoring/refactor/106.lua
lua/refactoring/tests/refactor/106/py/simple-function/extract.expected.py
lua/refactoring/treesitter/langs/python.lua
lua/refactoring/treesitter/treesitter.lua

@ThePrimeagen @pranavrao145 
feat: Add python param types if present during extract func
Wanted review as I am doing an override with treesitter here for python for a function. Wanted to make sure we are alright with overriding default treesitter behavior here for python arg param type key. We could probably override functions for other languages for specific operations so that the main refactor operations stay generic as possible.

feat: Add python param types if present during extract func

---

scripts/minimal.vim

fix: add nvim-treesitter to minimal.vim runtime

fix: add nvim-treesitter to minimal.vim runtime

---

README.md
lua/refactoring/debug/print_var.lua

As discussed in #312, this PR makes the default behaviour of print_var to find the variable under the cursor, regardless of mode, instead of simply printing whatever is in the visual selection. This means that, regardless of whether the user is in visual or normal mode, the behaviour is the same. Existing configs will not error out, but at the same time, the behavior will be smarter.
@teddylear take a look and let me know what you think!

Change print var to always attempt to find variable, regardless of mode

---

README.md
lua/refactoring/debug/print_var.lua

Reverting #314 because it caused some weird behaviour when attempting to print out certain statements, such as in #316. This means that this plugin will **still support normal mode,** it just will also still support custom printing using visual mode.

Revert "Change print var to always attempt to find variable, regardless of mode

---

README.md
lua/refactoring/utils.lua

@teddylear This will fix the issue outlined by #235. Turns out the check in the utils to see if the node was included in the given containing node was not inclusive, causing problems if there was nothing else on the line after the expression to be extracted. Just wanted to see what you thought about this before merging because it messes with the utils, but on the other hand it should fix the problem for any language in the future. Take a look and let me know what you think!
P.S. You can disregard the second commit, just an inconsistency I spotted in the README, might as well just do it in the same PR.

fix(python-extract-bloc): added special condition for extract var where there is nothing after the expression to extract on the same line

---

.github/workflows/format.yml
lua/refactoring/refactor/106.lua
lua/refactoring/treesitter/langs/python.lua

refactor: Use treesitter predicate functions to remove 'self' keyword when capturing python variables. I had no idea these were a thing
Also update formatting CI task to latest. 
@pranavrao145 Sorry I haven't gotten a chance to work on this in a while, trying to get back into it again. Saw treesitter predicate functions at neovim conf and had no idea these were a thing. It will make removing certain keywords a lot easier along with some complex treesitter queries.

refactor: Use treesitter predicate functions to remove 'self' keyword when capturing python variables. I had no idea these were a thing

---

lua/refactoring/init.lua

Thanks for your efforts on this plugin 💙 
I've tried using this plugin in the past but it didn't work for me when following the [Using Built-In Neovim Selection](https://github.com/ThePrimeagen/refactoring.nvim#using-built-in-neovim-selection) setup. I would pick a refactoring and nothing would happen. I did some investigation and the problem is that `select_refactor` didn't receive my selection so `M.refactor` is never called.
The problem here seems to be the `selected_refactor` variable is evaluated before the internal async function in `get_select_input` is resolved.
Moving the evaluation into the `async.run` solves the issue.

Fix(select_refactor): properly return a value

---

lua/refactoring/dev.lua
lua/refactoring/query.lua
lua/refactoring/refactor/123.lua
lua/refactoring/tests/treesitter/treesitter_spec.lua
lua/refactoring/tests/utils_spec.lua
lua/refactoring/treesitter/nodes.lua
lua/refactoring/treesitter/treesitter.lua
lua/refactoring/utils.lua

There are some functions that are deprecated and will be removed in the next nvim version:
vim.treesitter.parse_query() is deprecated, use vim.treesitter.query.parse_query() instead. :help deprecated
This feature will be removed in Nvim version 0.10
vim.treesitter.query.parse_query() is deprecated, use vim.treesitter.query.parse() instead. :help deprecated
This feature will be removed in Nvim version 0.10
vim.treesitter.get_query() is deprecated, use vim.treesitter.query.get_query() instead. :help deprecated
This feature will be removed in Nvim version 0.10
vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10

fix: change deprecated code

---

lua/refactoring/debug/print_var.lua
lua/refactoring/debug/printf.lua
lua/refactoring/get_input.lua
lua/refactoring/get_select_input.lua
lua/refactoring/init.lua
lua/refactoring/lsp.lua
lua/refactoring/lsp_utils.lua
lua/refactoring/pipeline/init.lua
lua/refactoring/refactor/106.lua
lua/refactoring/refactor/119.lua
lua/refactoring/refactor/123.lua
lua/refactoring/region.lua
lua/refactoring/tasks/apply_text_edits.lua
lua/refactoring/tasks/create_file.lua
lua/refactoring/tasks/ensure_code_gen.lua
lua/refactoring/tasks/refactor_setup.lua
lua/refactoring/tests/lsp_utils_spec.lua
lua/refactoring/tests/refactor_spec.lua
lua/refactoring/tests/region_spec.lua
lua/refactoring/treesitter/langs/go.lua
lua/refactoring/treesitter/treesitter.lua
lua/refactoring/ts.lua
lua/refactoring/utils.lua
scripts/minimal.vim

This PR fixes #373 (a small change, as described on the issue), uses `Pipeline`  to stop the execution whenever an error occurs (showing the error message via `vim.notify`. Should I add some kind of option to override this?) fixing #358 (if a user doesn't enter a variable name o a file name, the pipeline is stopped and an error message is showed via `vim.notify`) and cleans/refactors some code.
For example, the issue solved by #355 was related to an old workaround on `lsp_utils.lua` (using the same `start` and `end` for an lsp_range used to cause problems. The issue is solved now, so the workaround is no longer needed). As a consecuense of this change, it's possible to differentitate between lsp_ranges where text is going to be inserted and where text is going to be replaced.

Fix #373. Fix #358

---

lua/refactoring/command.lua
lua/refactoring/init.lua

Details: this affects lua/refactoring/init.lua (run when calling `setup`) and lua/refactoring/command.lua (run on startup)

perf: do not eagerly require modules on init

---

lua/refactoring/code_generation/langs/php.lua
lua/refactoring/config/init.lua
lua/refactoring/refactor/106.lua

When the extract function is inside a class pass the visibility keyword as an option. Currently it is only "wired" to work with php classes.
I don't know if this is the best approach  or even if this feature is wanted, but as a user i thought it would be nice to have.
I would appreciate some feedback if it needs changes or additions to be complete.

feat(extract_func): make visibility keyword configurable for classes

---

lua/refactoring/query.lua
lua/refactoring/treesitter/treesitter.lua
lua/refactoring/ts-locals.lua
queries/php/locals.scm

BREAKING CHANGE: nvim-treesitter changed the format of local captures to follow the upstream format, we are doin the same.
Should fix #432

feat(ts-locals)!: switch to upstream captures

---

lua/refactoring/refactor/106.lua
lua/refactoring/refactor/119.lua
lua/refactoring/refactor/123.lua
lua/refactoring/tasks/post_refactor.lua

This is a small PR that just improves the styling if the user has set `show_success_message = true`.
before:
after:

feat(success_message): improve notification styling

---

lua/refactoring/code_generation/langs/python.lua
lua/refactoring/tests/refactor/106/py/class-return/extract.expected.py
lua/refactoring/tests/refactor/106/py/multiple-returns/extract.expected.py
lua/refactoring/tests/refactor/106/py/with-imports/extract.expected.py

Currently if we have the following code:
```python
def main():
x = 1
y = 2
z = x + y
print(z)
```
The `Extract Function`, after providing the parameters and return type, generates the following code:
```python
def sum(x: int, y: int):
z = x + y
return z
def main():
x = 1
y = 2
z = sum(x, y)
print(z)
```
When it should be:
```python
def sum(x: int, y: int) -> int:
z = x + y
return z
def main():
x = 1
y = 2
z = sum(x, y)
print(z)
```
This pull request tries to fix it!
The changes are tested locally and it works ok.

Add return type when extracting to function in Python

---

lua/refactoring/tasks/create_file.lua

This secures the assumption of other tasks that the user is in the window were the refactor started when they are executed
Fixes #474 (once more)

fix(106): return to initial window after creating new file

---

lua/refactoring/tasks/apply_text_edits.lua
lua/refactoring/treesitter/langs/lua.lua

Additional apply_text_edtits fix because of https://github.com/neovim/neovim/pull/29877

fix(lua-123): add filter to handle `{foo = foo}`

---

README.md

The :Refactor command doesn't work if the plugin isn't yet loaded.  Instead, load non-lazy.  Alternative would be to use `cmd = 'Refactor'`, but I haven't tested that.

Lazy.nvim should be less lazy

---

lua/refactoring/refactor/106.lua

Hello there!
Nightly has a breaking changes to `query:iter_matches` that broken 106 actions.
I tested this manually using the snippets in `tests/refactor/106/cpp` for normal and range actions in nightly.
From what I'm seeing in the gh actions logs, it seems to fix a couple of tests but not all that are currently failing in master.
Thanks!

fix(106): iter_matches backwards compatibility for nightly

---

README.md
lua/refactoring/init.lua

Added second boolean argument `useExCmd` to select_refactor to allow adding arguments to the Ex command and get the preview of changes.
Let me know any change you think appropiated.
Closes #491

feat: add useExCmd option to select_refactor()

---

lua/refactoring/debug/debug_utils.lua
lua/refactoring/debug/init.lua
lua/refactoring/debug/print_var.lua
lua/refactoring/treesitter/langs/javascript.lua
lua/refactoring/treesitter/langs/typescript.lua
lua/refactoring/treesitter/langs/typescriptreact.lua

This also adds more statement and indent_scope nodes for js/ts/tsx

fix(debug): only use the location of the first non-blank character if it's greater than the cursor location

---

README.md

According to [lazy.nvim's documentation](https://lazy.folke.io/spec), it is recommended to use the `opts` field for configuring plugins, rather than providing a `config` function which calls the plugin's `setup` function:
> `config` is executed when the plugin loads. The default implementation will automatically run `require(MAIN).setup(opts)` if `opts` or `config = true` is set. Lazy uses several heuristics to determine the plugin's `MAIN` module automatically based on the plugin's **name**. _(`opts` is the recommended way to configure plugins)_.
This PR changes the README's example for installation with lazy.nvim to use the recommended `opts` field instead of the `config` one.

docs: Use opts field for lazy.nvim example in README
